trigger:
  - develop/*
pool:
  vmImage: 'macos-latest'

variables:
  - group: iotc-cpm-android
  - name: CPM_DEBUG_PROJECT_NAME
    value: $(Project_Name)
  - name: CPM_RELEASE_PROJECT_NAME
    value: $(Project_Name)

name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
  # - job: Android_Develop
  #   condition: and(succeeded(), eq(variables.isMaster, false))
  #   steps:
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: '12.18.4'
  #       displayName: 'Install Node'

  #     - script: npm install
  #       workingDirectory: .
  #       displayName: 'Install node dependencies'

  #     - script: npm version prerelease --preid "$(Build.BuildNumber)" --no-git-tag-version
  #       workingDirectory: .
  #       displayName: 'Increment version in package.json'

  #     - task: Gradle@2
  #       inputs:
  #         workingDirectory: 'android'
  #         gradleWrapperFile: 'android/gradlew'
  #         gradleOptions: '-Xmx3072m'
  #         publishJUnitResults: false
  #         testResultsFiles: '**/TEST-*.xml'
  #         tasks: 'assembleDebug'

  #     - task: PublishBuildArtifacts@1
  #       displayName: 'Publish Build Artifact'
  #       inputs:
  #         PathtoPublish: 'android/app/build/outputs/apk/debug/$(Project_Name)-debug.apk'
  #         ArtifactName: 'android'
  #         publishLocation: 'Container'

  - job: Android_Release
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.18.4'
        displayName: 'Install Node'

      - script: npm install
        workingDirectory: .
        displayName: 'Install node dependencies'

      - script: npm version prerelease --preid "$(Build.BuildNumber)" --no-git-tag-version
        workingDirectory: .
        displayName: 'Increment version in package.json'

      - task: DownloadSecureFile@1
        name: androidKeystore
        inputs:
          secureFile: iotc-cpm-release.keystore

      - bash: |
          CPM_RELEASE_VERSION_CODE=$(echo $(Build.BuildNumber) | sed 's/\.//')
          echo "##vso[task.setvariable variable=CPM_RELEASE_VERSION_CODE]$CPM_RELEASE_VERSION_CODE"
          cp $(androidKeystore.secureFilePath) android/app/$CPM_RELEASE_STORE_FILE
          ls -l android/app/$CPM_RELEASE_STORE_FILE

      - bash: env | sort

      - task: Gradle@2
        env:
          KEYSTORE_PASSWORD: $(CPM_RELEASE_STORE_PASSWORD)
          KEYSTORE: $(CPM_RELEASE_STORE_FILE)
          KEY_ALIAS: $(CPM_RELEASE_KEY_ALIAS)
          KEY_PASSWORD: $(CPM_RELEASE_KEY_PASSWORD)
        inputs:
          workingDirectory: 'android'
          gradleWrapperFile: 'android/gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'assembleRelease'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Build Artifact'
        inputs:
          PathtoPublish: 'android/app/build/outputs/apk/release/$(Project_Name)-release.apk'
          ArtifactName: 'android'
          publishLocation: 'Container'
