pool:
  vmImage: 'macOS-12'

variables:
  - group: iotc-cpm-android
  - name: CPM_DEBUG_PROJECT_NAME
    value: $(Project_Name)
  - name: CPM_RELEASE_PROJECT_NAME
    value: $(Project_Name)
  - name: rootPath
    value: '$(System.DefaultWorkingDirectory)'

name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
  - job: iOS_Release
    timeoutInMinutes: 120
    variables:
      rootPath: '$(System.DefaultWorkingDirectory)'
      agentName: $[ dependencies.Setup.outputs['passOutput.AgentName'] ]
      archivePath: '$(rootPath)/output/archive'
      xcodeDeveloperDir: '/Applications/Xcode_13.3.1.app/Contents/Developer'
      xcarchivePath: '$(archivePath)/$(Project_Name).xcarchive'
      zipToSign: '$(archivePath)/$(Project_Name).zip'
      signedZip: '$(archivePath)/$(Project_Name).zip'
      signedExtractedPath: '$(exportPath)/signed'
    steps:
      - template: ./node-build.yml
      - bash: npm run podinstall
      - task: DownloadSecureFile@1
        displayName: 'Download distribution profile from Azure secure files storage'
        inputs:
          secureFile: 'CPM_Dogfood.mobileprovision'
          retryCount: 5

      - task: CopyFiles@2
        displayName: 'Copy distribution provisioning profile'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: 'CPM_Dogfood.mobileprovision'
          TargetFolder: '$(archivePath)'
          flattenFolders: true

      - task: CopyFiles@2
        displayName: 'Copy ExportOptions'
        inputs:
          SourceFolder: '$(rootPath)'
          Contents: 'ExportOptions.plist'
          TargetFolder: '$(archivePath)'
          flattenFolders: true

      - task: Xcode@5
        displayName: 'Build Mobile Application'
        inputs:
          actions: 'build archive'
          configuration: 'Release'
          xcWorkspacePath: '$(rootPath)/ios/$(Project_Name).xcworkspace'
          scheme: '$(Project_Name)'
          sdk: 'iphoneos15.4'
          useXcpretty: false
          archivePath: '$(xcarchivePath)'
          args: '-archivePath $(xcarchivePath)'
          xcodeVersion: 'specifyPath'
          xcodeDeveloperDir: '$(xcodeDeveloperDir)'

      - task: ArchiveFiles@2
        displayName: 'Create zip for signing'
        inputs:
          rootFolderOrFile: '$(archivePath)'
          includeRootFolder: false
          archiveFile: '$(zipToSign)'
      
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk(temporary)'
        inputs:
          packageType: sdk
          version: 2.1.x
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: EsrpCodeSigning@1
        displayName: 'Sign build'
        inputs:
          ConnectedServiceName: 'IoT PnP PaaD'
          FolderPath: '$(archivePath)'
          Pattern: '*.zip'
          signConfigType: 'inlineSignParams'
          inlineOperation: |
            [
                  {
                      "KeyCode" : "CP-464234-Apple",
                      "OperationCode" : "iOSAppSign",
                      "Parameters" : {},
                      "ToolName" : "sign",
                      "ToolVersion" : "1.0"
                  }
            ]
          SessionTimeout: '60'
          MaxConcurrency: '50'
          MaxRetryAttempts: '5'

      - task: ExtractFiles@1
        displayName: 'Extract signed build'
        inputs:
          archiveFilePatterns: '$(signedZip)'
          destinationFolder: '$(signedExtractedPath)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Signed Ipa'
        inputs:
          PathtoPublish: '$(signedExtractedPath)'
          ArtifactName: 'ios_signed'
          publishLocation: 'Container'

  # - job: Android_Release
  #   steps:
  #     - template: ./node-build.yml
  #     - task: DownloadSecureFile@1
  #       name: androidKeystore
  #       inputs:
  #         secureFile: iotc-cpm-release.keystore

  #     - bash: |
  #         CPM_RELEASE_VERSION_CODE=$(echo $(Build.BuildNumber) | sed 's/\.//')
  #         echo "##vso[task.setvariable variable=CPM_RELEASE_VERSION_CODE]$CPM_RELEASE_VERSION_CODE"
  #         cp $(androidKeystore.secureFilePath) android/app/$CPM_RELEASE_STORE_FILE
  #         ls -l android/app/$CPM_RELEASE_STORE_FILE

  #     - bash: env | sort

  #     - bash: npx jetify

  #     - task: Gradle@2
  #       env:
  #         KEYSTORE_PASSWORD: $(CPM_RELEASE_STORE_PASSWORD)
  #         KEYSTORE: $(CPM_RELEASE_STORE_FILE)
  #         KEY_ALIAS: $(CPM_RELEASE_KEY_ALIAS)
  #         KEY_PASSWORD: $(CPM_RELEASE_KEY_PASSWORD)
  #       inputs:
  #         workingDirectory: 'android'
  #         gradleWrapperFile: 'android/gradlew'
  #         gradleOptions: '-Xmx3072m'
  #         publishJUnitResults: false
  #         testResultsFiles: '**/TEST-*.xml'
  #         tasks: 'assembleRelease'

  #     - task: PublishBuildArtifacts@1
  #       displayName: 'Publish Build Artifact'
  #       inputs:
  #         PathtoPublish: 'android/app/build/outputs/apk/release/$(Project_Name)-release.apk'
  #         ArtifactName: 'android'
  #         publishLocation: 'Container'
